version: '3.8'

services:
  # Python Retriever Agent
  retriever-agent:
    build: ./python-retriever
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./python-retriever:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Application
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RETRIEVER_AGENT_URL=http://retriever-agent:8000
    depends_on:
      retriever-agent:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  # Supabase (if using local instance)
  # supabase:
  #   image: supabase/postgres:15.1.0.117
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - supabase_db:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   supabase_db: